### ISSUE TITLE
ProcessedText does not cater for SYNTHETIC type

### ISSUE THREAD

**Issue by jojo-data** [privateai/pai-thin-client#4]
The `ProcessedText` class has validators for both `type` and `pattern`; the default `pattern` is assigned if not specified. However, when you specify `SYNTHETIC` as the value for `type`, `pattern` is supposed to be left out in the request payload. Otherwise, you will have the following error.

```text
{'detail': [{'msg': 'extra fields not permitted', 'loc': ['body', 'processed_text', 'SyntheticRedactedText', 'pattern'], 'type': 'value_error.extra'}]}
```

Specify `pattern` as None also won't work since the validator is in place.

**Comment by jojo-data** [comment]
hacky fix would be like
```python
if self._type == "MARKER" and self._pattern_validator(pattern):
```
instead of 
https://github.com/privateai/pai-thin-client/blob/20083b8ce792f2e0678f131575c42f58ecac24ad/src/privateai_client/components/request_objects.py#L253

**Comment by koryf** [comment]
Thanks for this @jojo-data. We'll get a fix in for this shortly

**Comment by a-guiducci** [comment]
@jojo-data  version 1.2 is released and has addressed this issue! Users can now create processed text objects for all 3 types (synthetic, marker and mask) with the correct attributes
