### ISSUE TITLE
Missing `image_options` in `ProcessFileBase64Request`

### ISSUE THREAD

**Issue by LilianJim** [privateai/pai-thin-client#42]
Hi,

It seems the [`ProcessFileBase64Request`](https://github.com/privateai/pai-thin-client/blob/515a40ac85972ef08ee540fb065742f7dfaad3d2/src/privateai_client/components/request_objects.py#L797) is missing the `image_options` parameter, [available in the API](https://docs.private-ai.com/reference/latest/operation/process_files_base64_v3_process_files_base64_post/#operation/process_files_base64_v3_process_files_base64_post!path=image_options&t=request)

**Comment by yaysummeriscoming** [comment]
Thanks for raising this @LilianJim we're working on a fix and will have that ready soon

**Comment by letmerecall** [comment]
@LilianJim `image_options` was introduced in #47
