### ISSUE TITLE
PAIClient does not support x-api-key header

### ISSUE THREAD

**Issue by jojo-data** [privateai/pai-thin-client#5]
The thin client does not support `x-api-key` in the header of the request, thus can not be used to send requests to hosted private ai API endpoints

**Comment by a-guiducci** [comment]
@jojo-data  The latest build is in pypi and has the capability to add x-api-key now :) 
Here's a sample of how to go about it:
#### Adding Authorization to the Client

```python
from privateai_client import PAIClient
# On initialization
client = PAIClient("http", "localhost", "8080", api_key='testkey')

# After initialization
client = PAIClient("http", "localhost", "8080")
client.add_api_key("testkey")
```

I'll keep this issue open for a couple days, just in case any unforeseen issues come up

**Comment by a-guiducci** [comment]
ability to add api key to the header of requests has been added in the latest release
